/**
 * SS2 runtime-capture wrapper (ActionScript 2, AVM1) — UNVALIDATED DRAFT.
 *
 * Independently authored instrumentation host for controlled 1v1 capture
 * sessions against the licensed Swords & Sandals II SWF identified in
 * docs/integration/ss2-build-fingerprint.json. It loads the installed file in
 * place (never a copy), never patches it, and emits only the JSONL trace
 * grammar from docs/integration/ss2-runtime-capture.md via trace().
 *
 * STATUS: this source cannot be compiled or executed yet — no AVM1-capable
 * player or AS2 compiler is installed. Before any emitted trace is trusted:
 *   1. an approved local player (Ruffle desktop preferred) must be installed;
 *   2. Object.watch, timeline-function wrapping, level loading, and the
 *      overlay instance path must be verified against that player;
 *   3. the wrapper must reproduce the reference traces generated by
 *      src/golden/simulate-capture-trace.js (modulo meta identity, passive
 *      roll values, and per-roll callSite attribution) for a staged
 *      candidate scenario.
 *
 * Runtime configuration arrives via FlashVars / loader query string — the
 * install path and session identity are never embedded in this file:
 *   gameUrl        file: URL of the installed swords_sandals2_download.swf
 *   observationId  token
 *   sessionId      token
 *   toolVersion    e.g. ss2-capture/0.1.0
 *   observedAt     ISO timestamp recorded by the operator
 *   hashBefore     "true" only after tools/capture-session.mjs verify-install
 *   attackerSide   "hero" (default) or "villain"
 *   injected       "true" => serve the fixture tape from randomBetween
 *   tape           comma list label:min:max:value in fixture order —
 *                  randomBetween samples ONLY (opcode debris rolls are
 *                  neither injectable nor recordable and are excluded from
 *                  observation matching)
 *   watchFields    comma list of game-object fields to watch (defaults below)
 *
 * The post-session hash attestation is NOT a launch parameter: the wrapper
 * emits the end line with a null placeholder, and capture-session.mjs ingest
 * re-runs the install hash check live and stamps the attestation only when
 * it passes.
 *
 * Operator flow: a lethal action finishes automatically after the overlay
 * result label; for non-lethal captures press END after the action resolves
 * to dump final state and close the trace.
 */

// ---------------------------------------------------------------------------
// Minimal JSON emitter (AS2 has no JSON object). Numbers, booleans, strings,
// flat objects, and arrays only — exactly what the trace grammar needs.
// ---------------------------------------------------------------------------
function jsonString(value) {
    var type = typeof value;
    if (value == null) return "null";
    if (type == "number" || type == "boolean") return String(value);
    if (type == "string") {
        var out = "\"";
        for (var i = 0; i < value.length; i++) {
            var c = value.charAt(i);
            if (c == "\"" || c == "\\") out += "\\" + c;
            else if (c == "\r") out += "\\r";
            else if (c == "\n") out += "\\n";
            else if (c == "\t") out += "\\t";
            else out += c;
        }
        return out + "\"";
    }
    if (value instanceof Array) {
        var items = [];
        for (var a = 0; a < value.length; a++) items.push(jsonString(value[a]));
        return "[" + items.join(",") + "]";
    }
    var pairs = [];
    for (var key in value) pairs.push(jsonString(key) + ":" + jsonString(value[key]));
    return "{" + pairs.join(",") + "}";
}

function emit(line) {
    trace(jsonString(line)); // Ruffle desktop: RUST_LOG=avm_trace=info captures this
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------
var config = {
    gameUrl: _root.gameUrl,
    observationId: _root.observationId,
    sessionId: _root.sessionId,
    toolVersion: _root.toolVersion,
    observedAt: _root.observedAt,
    hashBefore: _root.hashBefore == "true",
    attackerSide: _root.attackerSide == "villain" ? "villain" : "hero",
    injected: _root.injected == "true"
};

// FlashVars land as _root properties, and timeline vars ARE _root
// properties, so the raw string MUST be captured before any variable named
// "tape" is declared (validated the hard way: `var tape = []` silently
// clobbers the -Ptape FlashVar).
var rawTape = _root.tape;
var tape = [];      // [{label, min, max, value}] in fixture order
var tapeCursor = 0;
if (rawTape != undefined && rawTape != "") {
    var entries = rawTape.split(",");
    for (var t = 0; t < entries.length; t++) {
        var parts = entries[t].split(":");
        tape.push({ label: parts[0], min: Number(parts[1]), max: Number(parts[2]), value: Number(parts[3]) });
    }
}

var DEFAULT_WATCH_FIELDS = [
    // the 18 projected fields ...
    "hitpoints", "armourclass", "armourclass_max", "staminaleft",
    "burning", "frozen", "poison", "life_stolen", "taunted1", "taunted2",
    "helmet", "shoulderguard", "breastplate", "gauntlet", "greaves",
    "shinguard", "boot", "shield",
    // ... plus staged-scenario inputs so ingest chain checks always anchor
    "attack", "defence", "strength", "charisma", "magicka",
    "min_damage", "max_damage", "hitpointsmax", "staminamax", "ammo_left"
];
var watchFields = _root.watchFields != undefined && _root.watchFields != ""
    ? _root.watchFields.split(",")
    : DEFAULT_WATCH_FIELDS;

// Block-level call sites for the wrapped randomBetween definitions.
var OVERLAY_CALL_SITE = "overlay:862/frame:52/DoAction@0x240c7f";
var ROOT_CALL_SITE = "root:0/frame:35/DoAction@0x40198e";

emit({
    t: "meta",
    schemaVersion: 1,
    observationId: config.observationId,
    sessionId: config.sessionId,
    captureToolVersion: config.toolVersion,
    method: config.injected ? "injected-tape-runtime" : "passive-runtime",
    observedAt: config.observedAt,
    mutationGranularity: "property-watch",
    installHashVerifiedBefore: config.hashBefore,
    attackerSide: config.attackerSide
});

// ---------------------------------------------------------------------------
// Load the installed game in place, on its own level so its _root stays its
// own root timeline (no _lockroot juggling, no changes to the loaded movie).
// ---------------------------------------------------------------------------
loadMovieNum(config.gameUrl, 1);

var currentHook = "unattributed";   // set/cleared by function wraps
var battleHooked = false;
var stateDumped = false;
var finalsDumped = false;
var resultSeen = false;

function gameRoot() { return _level1; }
function gameObject(side) { return gameRoot().game[side == "hero" ? "hero" : "villain"]; }
// Byte-verified: root frame 221 runs
// _root.arena.gladiators.attachMovie("overlay", "overlay", 40000).
function overlayClip() { return gameRoot().arena.gladiators.overlay; }

function dumpSide(kind, side) {
    var source = gameObject(side);
    var fields = {};
    for (var i = 0; i < watchFields.length; i++) {
        var name = watchFields[i];
        if (source[name] !== undefined) fields[name] = source[name];
    }
    if (source.gladiator_dir !== undefined) fields.gladiator_dir = source.gladiator_dir;
    emit({ t: kind, side: side, fields: fields });
}

// Object.watch callback: fires per assignment, before the write lands.
function makeWatcher(side) {
    return function (prop, oldValue, newValue) {
        emit({
            t: "set",
            path: "/" + side + "/" + prop,
            before: oldValue,
            after: newValue,
            hook: currentHook
        });
        return newValue;
    };
}

function wrapHook(owner, name, hookLabel, onEnter) {
    var original = owner[name];
    if (typeof original != "function") return false;
    owner[name] = function () {
        var previous = currentHook;
        currentHook = hookLabel;
        if (onEnter != undefined) onEnter(arguments);
        var result = original.apply(this, arguments);
        currentHook = previous;
        return result;
    };
    return true;
}

function wrapRandomBetween(owner, siteId) {
    var original = owner.randomBetween;
    if (typeof original != "function") return false;
    owner.randomBetween = function (a, b) {
        var sample = tape[tapeCursor];
        var matches = sample != undefined && sample.min == a && sample.max == b;
        var value;
        var label;
        if (config.injected && matches) {
            value = sample.value;
            label = sample.label;
        } else {
            // Tape exhaustion or a bounds mismatch means the game diverged
            // from the candidate's expected roll order: fall back to the real
            // RNG and keep recording. NOTE: a session where NO tape entry
            // ever matched has zero injected samples and will be rejected by
            // observation validation; the raw JSONL in captures/ is then the
            // divergence evidence to correct the candidate from.
            value = original(a, b);
            label = matches ? sample.label : "unexpected-" + tapeCursor;
        }
        tapeCursor++;
        emit({
            t: "roll", label: label, source: "randomBetween",
            min: a, max: b, value: value,
            callSite: siteId, injected: config.injected && matches
        });
        return value;
    };
    return true;
}

function hookBattle() {
    var root = gameRoot();
    if (root == undefined || root.game == undefined) return;
    if (root.game.hero == undefined || root.game.villain == undefined) return;
    var overlay = overlayClip();
    if (overlay == undefined || typeof overlay.randomBetween != "function") return;

    wrapRandomBetween(overlay, OVERLAY_CALL_SITE);
    wrapRandomBetween(root, ROOT_CALL_SITE); // root frame 35 duplicate definition

    wrapHook(overlay, "checkattackroll", "check-attack-roll", function () {
        emit({ t: "var", name: "attack_direction", value: overlay.attack_direction });
        if (overlay.criticalhit != undefined) {
            emit({ t: "var", name: "criticalhit", value: overlay.criticalhit });
        }
    });
    wrapHook(overlay, "damagecharacter", "damagecharacter");
    wrapHook(overlay, "magic_damage_character", "damagecharacter");
    wrapHook(overlay, "remove_armour", "remove-armour");
    wrapHook(overlay, "destroy_armour", "remove-armour");
    wrapHook(overlay, "nextphase", "next-phase");
    wrapHook(overlay, "check_spells", "check-spells");
    wrapHook(overlay, "defender_hurt", "damagecharacter", function (args) {
        emit({ t: "event", type: "defender-hurt", method: String(args[0]) });
    });
    wrapHook(overlay, "defender_blocked", "check-attack-roll", function () {
        emit({ t: "event", type: "defender-blocked" });
    });
    wrapHook(overlay, "death", "death", function (args) {
        var clip = args[0];
        var side = clip == root.arena.gladiators.villain ? "villain" : "hero";
        emit({ t: "event", type: "death", side: side });
    });

    // Overlay result labels surface through gotoAndPlay on the controller.
    var originalGoto = overlay.gotoAndPlay;
    overlay.gotoAndPlay = function (label) {
        if (label == "combatwon" || label == "combatlost") {
            emit({ t: "event", type: "overlay-label", label: label });
            resultSeen = true;
        }
        return originalGoto.apply(this, arguments);
    };

    var sides = ["hero", "villain"];
    for (var s = 0; s < sides.length; s++) {
        var side = sides[s];
        var target = gameObject(side);
        for (var f = 0; f < watchFields.length; f++) {
            target.watch(watchFields[f], makeWatcher(side));
        }
    }
    battleHooked = true;
}

function finishTrace() {
    if (finalsDumped) return;
    dumpSide("final", "hero");
    dumpSide("final", "villain");
    // The post-session hash check has not run yet, so this attestation can
    // only be a placeholder; capture-session.mjs ingest re-runs the check
    // live and refuses the trace when it fails.
    emit({ t: "end", installHashVerifiedAfter: null });
    finalsDumped = true;
}

// END key closes a non-lethal capture once the action has resolved.
var keyListener = {
    onKeyDown: function () {
        if (Key.getCode() == Key.END && stateDumped) finishTrace();
    }
};
Key.addListener(keyListener);

// ---------------------------------------------------------------------------
// Driver loop: hook once the battle exists, dump staged state at
// battle_started, close automatically after a lethal overlay label.
// ---------------------------------------------------------------------------
this.onEnterFrame = function () {
    if (!battleHooked) { hookBattle(); return; }
    if (!stateDumped && _global.battle_started == true) {
        dumpSide("state", "hero");
        dumpSide("state", "villain");
        stateDumped = true;
    }
    if (resultSeen && !finalsDumped) finishTrace();
};
